/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class Date : TBase
{
  private short _day;
  private short _month;
  private short _year;

  public short Day
  {
    get
    {
      return _day;
    }
    set
    {
      __isset.day = true;
      this._day = value;
    }
  }

  public short Month
  {
    get
    {
      return _month;
    }
    set
    {
      __isset.month = true;
      this._month = value;
    }
  }

  public short Year
  {
    get
    {
      return _year;
    }
    set
    {
      __isset.year = true;
      this._year = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool day;
    public bool month;
    public bool year;
  }

  public Date()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I16)
            {
              Day = await iprot.ReadI16Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I16)
            {
              Month = await iprot.ReadI16Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.I16)
            {
              Year = await iprot.ReadI16Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("Date");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (__isset.day)
      {
        field.Name = "day";
        field.Type = TType.I16;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI16Async(Day, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.month)
      {
        field.Name = "month";
        field.Type = TType.I16;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI16Async(Month, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.year)
      {
        field.Name = "year";
        field.Type = TType.I16;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI16Async(Year, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as Date;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.day == other.__isset.day) && ((!__isset.day) || (System.Object.Equals(Day, other.Day))))
      && ((__isset.month == other.__isset.month) && ((!__isset.month) || (System.Object.Equals(Month, other.Month))))
      && ((__isset.year == other.__isset.year) && ((!__isset.year) || (System.Object.Equals(Year, other.Year))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.day)
        hashcode = (hashcode * 397) + Day.GetHashCode();
      if(__isset.month)
        hashcode = (hashcode * 397) + Month.GetHashCode();
      if(__isset.year)
        hashcode = (hashcode * 397) + Year.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("Date(");
    bool __first = true;
    if (__isset.day)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Day: ");
      sb.Append(Day);
    }
    if (__isset.month)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Month: ");
      sb.Append(Month);
    }
    if (__isset.year)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Year: ");
      sb.Append(Year);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

