/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



/// <summary>
/// This exception is thrown by SError procedures when a call fails as a result of
/// a problem in the service that could not be changed through caller action.
/// 
/// error_code: The numeric code indicating the type of error that occurred.
/// Must be one of the values of SErrorType
/// 
/// message: This may contain additional information about the error.
/// 
/// rateLimitDuration: Indicates the minimum number of seconds that an application
/// should expect subsequent API calls for this user to fail.
/// </summary>
public partial class SErrorSystemException : TException, TBase
{
  private string _message;
  private int _rateLimitDuration;

  /// <summary>
  /// 
  /// <seealso cref="SErrorType"/>
  /// </summary>
  public SErrorType Error_code { get; set; }

  public string Message
  {
    get
    {
      return _message;
    }
    set
    {
      __isset.message = true;
      this._message = value;
    }
  }

  public int RateLimitDuration
  {
    get
    {
      return _rateLimitDuration;
    }
    set
    {
      __isset.rateLimitDuration = true;
      this._rateLimitDuration = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool message;
    public bool rateLimitDuration;
  }

  public SErrorSystemException()
  {
  }

  public SErrorSystemException(SErrorType error_code) : this()
  {
    this.Error_code = error_code;
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_error_code = false;
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32)
            {
              Error_code = (SErrorType)await iprot.ReadI32Async(cancellationToken);
              isset_error_code = true;
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              Message = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.I32)
            {
              RateLimitDuration = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
      if (!isset_error_code)
      {
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("SErrorSystemException");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      field.Name = "error_code";
      field.Type = TType.I32;
      field.ID = 1;
      await oprot.WriteFieldBeginAsync(field, cancellationToken);
      await oprot.WriteI32Async((int)Error_code, cancellationToken);
      await oprot.WriteFieldEndAsync(cancellationToken);
      if (Message != null && __isset.message)
      {
        field.Name = "message";
        field.Type = TType.String;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(Message, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.rateLimitDuration)
      {
        field.Name = "rateLimitDuration";
        field.Type = TType.I32;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async(RateLimitDuration, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as SErrorSystemException;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return System.Object.Equals(Error_code, other.Error_code)
      && ((__isset.message == other.__isset.message) && ((!__isset.message) || (System.Object.Equals(Message, other.Message))))
      && ((__isset.rateLimitDuration == other.__isset.rateLimitDuration) && ((!__isset.rateLimitDuration) || (System.Object.Equals(RateLimitDuration, other.RateLimitDuration))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      hashcode = (hashcode * 397) + Error_code.GetHashCode();
      if(__isset.message)
        hashcode = (hashcode * 397) + Message.GetHashCode();
      if(__isset.rateLimitDuration)
        hashcode = (hashcode * 397) + RateLimitDuration.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("SErrorSystemException(");
    sb.Append(", Error_code: ");
    sb.Append(Error_code);
    if (Message != null && __isset.message)
    {
      sb.Append(", Message: ");
      sb.Append(Message);
    }
    if (__isset.rateLimitDuration)
    {
      sb.Append(", RateLimitDuration: ");
      sb.Append(RateLimitDuration);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

