/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



/// <summary>
/// Application Programming Interface definition for Spotijake Streaming Services.
/// this parent thrift file is contains all service interfaces. The data models are
/// described in respective thrift files.
/// </summary>
public partial class RequestTrackAudio : TBase
{
  private string _filename;

  public string Filename
  {
    get
    {
      return _filename;
    }
    set
    {
      __isset.filename = true;
      this._filename = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool filename;
  }

  public RequestTrackAudio()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              Filename = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("RequestTrackAudio");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (Filename != null && __isset.filename)
      {
        field.Name = "filename";
        field.Type = TType.String;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(Filename, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as RequestTrackAudio;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.filename == other.__isset.filename) && ((!__isset.filename) || (System.Object.Equals(Filename, other.Filename))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.filename)
        hashcode = (hashcode * 397) + Filename.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("RequestTrackAudio(");
    bool __first = true;
    if (Filename != null && __isset.filename)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Filename: ");
      sb.Append(Filename);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

