/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum MusicGender
{
  Pop = 1,
  Rock = 2,
  Bachata = 3,
  Balada = 4,
  Blues = 5,
  Clasica = 6,
  Corrido = 7,
  Country = 8,
  Cumbia = 9,
  Electronica = 10,
  Flamenco = 11,
  Reggaeton = 12,
  Punk = 13,
  Funk = 14,
  Metal = 15,
  HipHop = 16,
  Indie = 17,
  Jazz = 18,
  Merengue = 19,
  Salsa = 20,
  Reggae = 21,
  RocknRoll = 22,
  Ska = 23,
  Trap = 24,
  Son = 25,
  Vals = 26,
  Ranchero = 27,
  BosaNova = 28,
  Bolero = 29,
  Disco = 30,
}
