/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

/// <summary>
/// Application Programming Interface definition for Spotijake Streaming Services.
/// this parent thrift file is contains all service interfaces. The data models are
/// described in respective thrift files.
/// </summary>
public enum Quality
{
  HIGH = 0,
  MIDDLE = 1,
  LOW = 2,
}
