/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class RelatedResult : TBase
{
  private List<Track> _Tracks;
  private List<Album> _Albums;
  private List<Playlist> _Playlists;
  private List<ContentCreator> _ContentCreators;

  public List<Track> Tracks
  {
    get
    {
      return _Tracks;
    }
    set
    {
      __isset.Tracks = true;
      this._Tracks = value;
    }
  }

  public List<Album> Albums
  {
    get
    {
      return _Albums;
    }
    set
    {
      __isset.Albums = true;
      this._Albums = value;
    }
  }

  public List<Playlist> Playlists
  {
    get
    {
      return _Playlists;
    }
    set
    {
      __isset.Playlists = true;
      this._Playlists = value;
    }
  }

  public List<ContentCreator> ContentCreators
  {
    get
    {
      return _ContentCreators;
    }
    set
    {
      __isset.ContentCreators = true;
      this._ContentCreators = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool Tracks;
    public bool Albums;
    public bool Playlists;
    public bool ContentCreators;
  }

  public RelatedResult()
  {
    this._Tracks = new List<Track>();
    this.__isset.Tracks = true;
    this._Albums = new List<Album>();
    this.__isset.Albums = true;
    this._Playlists = new List<Playlist>();
    this.__isset.Playlists = true;
    this._ContentCreators = new List<ContentCreator>();
    this.__isset.ContentCreators = true;
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List)
            {
              {
                TList _list24 = await iprot.ReadListBeginAsync(cancellationToken);
                Tracks = new List<Track>(_list24.Count);
                for(int _i25 = 0; _i25 < _list24.Count; ++_i25)
                {
                  Track _elem26;
                  _elem26 = new Track();
                  await _elem26.ReadAsync(iprot, cancellationToken);
                  Tracks.Add(_elem26);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.List)
            {
              {
                TList _list27 = await iprot.ReadListBeginAsync(cancellationToken);
                Albums = new List<Album>(_list27.Count);
                for(int _i28 = 0; _i28 < _list27.Count; ++_i28)
                {
                  Album _elem29;
                  _elem29 = new Album();
                  await _elem29.ReadAsync(iprot, cancellationToken);
                  Albums.Add(_elem29);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.List)
            {
              {
                TList _list30 = await iprot.ReadListBeginAsync(cancellationToken);
                Playlists = new List<Playlist>(_list30.Count);
                for(int _i31 = 0; _i31 < _list30.Count; ++_i31)
                {
                  Playlist _elem32;
                  _elem32 = new Playlist();
                  await _elem32.ReadAsync(iprot, cancellationToken);
                  Playlists.Add(_elem32);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.List)
            {
              {
                TList _list33 = await iprot.ReadListBeginAsync(cancellationToken);
                ContentCreators = new List<ContentCreator>(_list33.Count);
                for(int _i34 = 0; _i34 < _list33.Count; ++_i34)
                {
                  ContentCreator _elem35;
                  _elem35 = new ContentCreator();
                  await _elem35.ReadAsync(iprot, cancellationToken);
                  ContentCreators.Add(_elem35);
                }
                await iprot.ReadListEndAsync(cancellationToken);
              }
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("RelatedResult");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (Tracks != null && __isset.Tracks)
      {
        field.Name = "Tracks";
        field.Type = TType.List;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Tracks.Count), cancellationToken);
          foreach (Track _iter36 in Tracks)
          {
            await _iter36.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Albums != null && __isset.Albums)
      {
        field.Name = "Albums";
        field.Type = TType.List;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Albums.Count), cancellationToken);
          foreach (Album _iter37 in Albums)
          {
            await _iter37.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Playlists != null && __isset.Playlists)
      {
        field.Name = "Playlists";
        field.Type = TType.List;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, Playlists.Count), cancellationToken);
          foreach (Playlist _iter38 in Playlists)
          {
            await _iter38.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (ContentCreators != null && __isset.ContentCreators)
      {
        field.Name = "ContentCreators";
        field.Type = TType.List;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        {
          await oprot.WriteListBeginAsync(new TList(TType.Struct, ContentCreators.Count), cancellationToken);
          foreach (ContentCreator _iter39 in ContentCreators)
          {
            await _iter39.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
        }
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as RelatedResult;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.Tracks == other.__isset.Tracks) && ((!__isset.Tracks) || (TCollections.Equals(Tracks, other.Tracks))))
      && ((__isset.Albums == other.__isset.Albums) && ((!__isset.Albums) || (TCollections.Equals(Albums, other.Albums))))
      && ((__isset.Playlists == other.__isset.Playlists) && ((!__isset.Playlists) || (TCollections.Equals(Playlists, other.Playlists))))
      && ((__isset.ContentCreators == other.__isset.ContentCreators) && ((!__isset.ContentCreators) || (TCollections.Equals(ContentCreators, other.ContentCreators))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.Tracks)
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Tracks);
      if(__isset.Albums)
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Albums);
      if(__isset.Playlists)
        hashcode = (hashcode * 397) + TCollections.GetHashCode(Playlists);
      if(__isset.ContentCreators)
        hashcode = (hashcode * 397) + TCollections.GetHashCode(ContentCreators);
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("RelatedResult(");
    bool __first = true;
    if (Tracks != null && __isset.Tracks)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Tracks: ");
      sb.Append(Tracks);
    }
    if (Albums != null && __isset.Albums)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Albums: ");
      sb.Append(Albums);
    }
    if (Playlists != null && __isset.Playlists)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Playlists: ");
      sb.Append(Playlists);
    }
    if (ContentCreators != null && __isset.ContentCreators)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("ContentCreators: ");
      sb.Append(ContentCreators);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

